In [2]:
import pandas as pd
from toolkit.utils import prepare_dps_freq, display_analysis

## Introduction

This experiment is the first phase of our endevour to optimize the frontend of the race.
This optimization effort is done in a situation in which maximizing will hurt us on others.
(_e.g._, increasing frequency in most cases will favor the split time on one hand,
and would hurt the DPS as well as the physical condition of the swimmer). 

## About the results

Our experiment is consisted of 4-5 time of pairs of $25m$ interval, in linearily increasing cycle frequency.
The $X$ axis is the frequency (mesearued in cycles/minute),
the $Y$ axis represents the Distance-per-stroke (DPS), whereas the $Z$ axis is the measured speed.

## Note
The _Time_ columns represents the time of the surfaced swimming only, whereas the _Speed_ column is $25m$ divided by the total lap time - surfaced and submerged swimming. 

The experiment was done in a standard SCM pool.

## Tal (free)

In [3]:
import numpy as np


df_raw = pd.read_excel("omer/raw-data2.xlsx")
df_data = prepare_dps_freq(df_raw)

KeyError: 'measurement'

#

# Display

In [4]:
display(df_data.sort_values("Frequency"))
display_analysis(df_data)

NameError: name 'df_data' is not defined

In [5]:
display(df_raw)

   measurement  interval-time  id  distance
0     breakout          1.422   1       5.0
1        cycle          1.039   1       NaN
2        cycle          1.575   1       NaN
3        cycle          1.649   1       NaN
4        cycle          1.721   1       NaN
5        cycle          1.767   1       NaN
6        cycle          1.494   1       NaN
7        cycle          1.780   1       NaN
8        cycle          1.724   1       NaN
9        cycle          1.799   1       NaN
10    breakout          1.601   2       5.0
11       cycle          0.995   2       NaN
12       cycle          1.596   2       NaN
13       cycle          1.659   2       NaN
14       cycle          1.848   2       NaN
15       cycle          1.690   2       NaN
16       cycle          1.565   2       NaN
17       cycle          1.783   2       NaN
18       cycle          1.624   2       NaN
19       cycle          1.888   2       NaN
20       cycle          1.910   2       NaN
21    breakout          1.500   3       5.0
22       cycle          0.769   3       NaN
23       cycle          1.621   3       NaN
24       cycle          1.628   3       NaN
25       cycle          1.741   3       NaN
26       cycle          1.771   3       NaN
27       cycle          1.677   3       NaN
28       cycle          1.685   3       NaN
29       cycle          1.738   3       NaN
30       cycle          2.000   3       NaN
31       cycle          1.119   3       NaN
32    breakout          1.383   4       5.0
33       cycle          1.274   4       NaN
34       cycle          1.570   4       NaN
35       cycle          1.583   4       NaN
36       cycle          1.906   4       NaN
37       cycle          1.799   4       NaN
38       cycle          1.927   4       NaN
39       cycle          1.577   4       NaN
40       cycle          2.080   4       NaN
41       cycle          1.867   4       NaN
42       cycle          1.149   4       NaN